export const API = {
    login: 'api/user/login',
    getAllUsers: `api/user/get-user`,
    refreshToken: `api/user/refresh-token`,
    //patientHours: ,
    noPayrollActive: 'api/active-payroll/active-clients-report',
    bankUpload: 'api/file-transform/bank-upload',
    taxPayment: 'api/file-transform/tax-payment',
    taxCollection: 'api/file-transform/tax-collection',
    //newHire: ,
    earningCode: 'api/earning-codes/get-earning-codes-by-company-short-name',
    countryWage: 'api/listing/get-country-wages',
    addWage: 'api/wage-counter/add-wage-country',
    updatePerviousDate: 'api/wage-counter/update-wage-country',
    deleteWage: (id) => `api/wage-counter/wage/delete/${id}`,
    getWage: 'api/wage-counter/get-wages-country',
    countryLocation: 'api/listing/get-countries',
    updateWage: 'api/wage-counter/wage/update',
    costCenter: 'api/cost-centers/get-cost-center',
    getLocationCenterByCostCenter: (centId) => `api/location-center/get-location-center-by-cost-center-id/${centId}/2`,
    updateLocationCenter: `api/cost-centers/map-location-id`,
    costCenterMapping: (id) => `api/cost-centers/get-cost-center-mapping/${id}`,
    getEarningCodesByCompany: (companyId) => `api/earning-codes/get-earning-codes-by-company/${companyId}`,
    saveEarningCodes: (companyId) => `api/wage-parity-new/report/wage-parity/saved-earnings-codes/?companyId=${companyId}`,
    setWagePartiyEcs: `api/wage-parity/earnings-codes`,
    updateEarningCode: `api/earning-codes/update-earning-code`,
    wageParityReport: `api/wage-parity-new/retrieve-wage-parity-report`,
    defaultCostCenter: `api/cost-centers/default-cost-center`,
    defaultCostCenterByComponyShortCode: `api/cost-centers/get-default-cost-center-by-company-short-name`,
    getCostCenterByCompanyCode: `api/cost-centers/get-cost-center-by-company-code`,
    //getEins: (companyId) => `api/patient-hours/get-eins/${companyId}`,
    syncCompanyEins: companyShortName => `api/sync-report/sync-company-eins/${companyShortName}`,
    getAllCoordinators: `api/patient-hours/get-all-coordinators`,
    getCSRS: `api/no-active-payroll/get-csrs`,
    getLatePayroll: `api/late-payroll/late-payroll`,
    getLatePayrollDetail: `api/late-payroll/late-payroll-detail`,
    getSyncWageParity: `api/sync-report/sync-wage-parity`,
    getSyncCostCenter: (company) => `api/cost-centers/get-sync-cost-center/${company}`,
    getSyncTeamSupportRegister: `api/sync-report/sync-register-for-team-support`,
    syncPatientHourReport: `api/sync-report/sync-patient-hour-reports`,
    getSyncLatePayrollDetails: `api/sync-report/sync-late-payroll-details`,
    getSyncLatePayroll: `api/sync-report/sync-late-payrolls`,
    getSyncNoPayrollActivity: `api/sync-report/sync-no-payroll-activity`,
    getTeamSupportRegister: `api/team-support/team-support-registration`,
    getSyncUser: `api/sync-report/sync-users`,
    saveReportId: (companyId) => `api/patient-hours/patient-hours-report-settings/${companyId}`,
    getReportId: (companyId) => `api/patient-hours/patient-hours-report-settings/${companyId}`,
    getEarningCodesByCompanyReportSetting: (companyId) => `api/payroll/earnings-codes/?companyId=${companyId}`,
    setWageParityECS: `api/wage-parity/earnings-codes`,
    getSavedEarningsCodes: (companyId) => `api/wage-parity/saved-earnings-codes/?companyId=${companyId}`,
    backgroundTasks: `api/background-tasks/tasks`,
    updateBackgroundTasks: `api/background-tasks/task`,
    clientsByCompany: (companyId) => `api/clients/client/${companyId}`,
    updateClients: `api/clients/client`,
    getClients: `api/clients/clients`,
    exportEarningCode: `api/earning-codes/export-earning-code`,
    exportEarningCodeByCompanyid: (companyId) => `api/earning-codes/export-earning-code/${companyId}`,
    getDefaultEIN: (companyId) => `api/patient-hours/get-default-ein/${companyId}`,
    saveDefaultEIN: `api/patient-hours/create-default-ein`,
    //getPayrollDetails: (companyId) => ,
    getAnnualBilling: `api/annual-billing/by-client-all`,
    getBillingDiscrepancy: 'api/billing-services/discrepancy-report',
    getCsrAssignments: 'api/csr/csr-assignments',
    getManagementOverviewReport: 'api/management-overview/report',
    getSavedBillingServices: 'api/billing-services/all-saved',
    deleteBillingService: id => `api/billing-services/billing-service/${id}`,
    addUpdateBillingService: 'api/billing-services/add-update',
    getAccruals: 'api/accruals/accrual-totals-per-employee',
    getAccrualsNew: (company) => `api/accruals/accrual-totals-per-employee/${company}`,
    getMinWageLocationId: locationId => `api/wage-counter/get-wages-counter-by-id/${locationId}`,
    addRole: `api/role/add-role`,
    //roleList: company => ,
    updateRoleList: `api/role/update-role`,
    addPurchaseOrder: 'api/items/create-purchase-order',
    getPurchaseOrder: 'api/items/get-purchase-order',
    updatePurchaseOrder: 'api/items/update-purchase-order',
    addOutboundOrder: 'api/items/create-outbound-order',
    getOutboundOrder: 'api/items/get-outbound-order',
    updateOutboundOrder: 'api/items/update-outbound-order',
    //getRolePermission: (username) => ,
    getRoleConfig: `api/role/get-role-config`,
    getLogsHistory: 'api/logs/logs',
    getBgTaskLogs: 'api/logs/bg-tasks',
    syncEarningCodeByCompanyCode: (company) => `api/earning-codes/sync-earning-code-by-company/${company}`,
    addItemOrder: 'api/items/create-item-order',
    getItemsOrder: 'api/items/get-items-order',
    updateItemOrder: 'api/items/update-item-order',
    wageLocation: 'api/wage-setup/wage-location',
    wageRate: (id) => `api/wage-setup/wage-rate/${id}`,
    getLocationWage: `api/wage-setup/wage-locations`,
    getSyncPayroll: company => `api/payroll/sync-payroll/${company}`,
    getSyncPHPayrollPerCompany: company => `api/patient-hours/sync-ph/${company}`,
    saveFileUpload: `api/file/upload-file`,
    getItemStatus: `api/items/get-status`,
    getOrderTd: (orderId) => `api/items/get-purchase-by-order-id/${orderId}`,
    getOrderTdOutbound: (orderId) => `api/items/get-outbound-by-order-id/${orderId}`,
    addWarrantyExpiration: `api/items/add-warranty-expiration`,
    getWarrantyExpiration: (itemId) => `api/items/get-warranty-expiration/${itemId}`,
    getSerialNumber: `api/items/get-serial-number`,

    addSerialNumber: `api/items/add-serial-outbound`,
    getSummeryReport: `api/report/get-summery-reports`,
    getAutoGenerate: `api/items/get-auto-generate-orderId`,
    getLocationBlank: (orderId) => `api/location/get-location-blank/${orderId}`,
    addLocationBlank: `api/location/add-location-blank`,
    getItemByPurchaseOrder: `api/items/get-item-by-purchase-order`,
    getReportPermission: (params) => `api/permission/get-report-permission/${params}`,
    saveEmail: `api/email/add-email`,
    getEmail: `api/email/get-email`,
    getEmailHistory: `api/email/get-email-history`,
    saveTimeOffs: company => `api/accrual/update-time-offs/${company}`,
    //getTimeOffs: companyId => ,
    getCompanyByPermission: `api/email/get-company-by-permission`,
    removeEmail: (emailId) => `api/email/delete/${emailId}`,
    updateEmail: `api/email/update-email`,
    getCsrAssignments: `api/csr/csr-assignment-settings`,
    updateCsrAssignments: `api/csr/update-report-settings`,
    addCsrAssignments: `api/csr/add-csr-settings`,

    deleteCsrAssignments: (id) => `api/csr/csr-assignment-settings-delete/${id}`,
}